# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 06:02:34 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: snpsift-filter, revision: 13, authored by: adam.halstead
# https://precision.fda.gov/apps/app-F0f784009zvVGyXJvV2xv8Kv

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	openjdk-7-jre-headless

# Download app assets
RUN curl https://dl.dnanex.us/F/D/1b1Zf91qbgYzx3ZJ6FZGgzq2z6b3Zfx8vP7P5k1V/snpeff-snpsift-4.3b.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"variants_vcf\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Annotated\\ VCF\\ file\\\",\\\"help\\\":\\\"Annotated\\ VCF\\ file\\ \\ to\\ filter\\ and\\ manipulate\\\",\\\"default\\\":\\\"file-F0Pyk5j0JKGP2b79YVz3kp4Z\\\"\\},\\{\\\"name\\\":\\\"filter_expression\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Expression\\ filter\\\",\\\"help\\\":\\\"filter\\ VCF\\ files\\ using\\ arbitrary\\ expressions\\ e.g.\\ \\(QUAL\\ \\\\u003e\\ 30\\)\\\"\\},\\{\\\"name\\\":\\\"filtered_vcf_filename\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Filtered\\ VCF\\ filename\\\",\\\"help\\\":\\\"The\\ prefix\\ that\\ will\\ be\\ used\\ to\\ name\\ the\\ output\\ file.\\\",\\\"default\\\":\\\"filtered\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"filtered_vcf\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Filtered\\ VCF\\ file\\\",\\\"help\\\":\\\"Filtered\\ VCF\\ file\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-8\\\"\\},\\\"assets\\\":\\[\\\"file-F0PyG9j07FxfZj590J8Yzjkp\\\"\\],\\\"packages\\\":\\[\\\"openjdk-7-jre-headless\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"cat\\ \\\\\\\"\\$variants_vcf_path\\\\\\\"\\ \\|\\ java\\ -jar\\ SnpSift.jar\\ filter\\ \\\\\\\"\\$filter_expression\\\\\\\"\\ \\\\u003e\\ \\\\\\\"\\$filtered_vcf_filename\\\\\\\".vcf\\\\nemit\\ filtered_vcf\\ \\\\\\\"\\$filtered_vcf_filename\\\\\\\".vcf\\ \\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work